[package]
name = "n_queens_gen"
version = "0.1.0"
description = "Generates n-queen formulae for the SAT solver"
edition.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
clap.workspace = true
