[package]
name = "max_clique_gen"
version = "0.1.0"
description = "Converts a graph into a max-clique specification"
edition.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
clap.workspace = true
rustc-hash.workspace = true
csv.workspace = true