[package]
name = "sudoku_gen"
version = "0.1.0"
description = "Generates a random edge list formatted graph"
edition.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
clap.workspace = true